### ISSUE TITLE
Question about vocabularies

### ISSUE THREAD

**Issue by parklize** [w3c-social/social-vocab#3]
Hi @elf-pavlik. 
1. What's the relation between the living vocabularies here and the page below? Since the page below is trying to match (or propose) existing vocabularies to user stories but here (in GitHub) seems are defining new terms.

https://www.w3.org/wiki/Socialig/Vocabulary_TF/Mapping_API_User_Stories_to_Vocabulary_terms

Will these terms defined in GitHub matched later with existing ones proposed in the page or...
1. The qualified relation is very interesting which is creating recourse for the relationship, as the example in the link you shared below [1].
   I'm wondering if the relationship property appears in the resource again is necessary and maybe the rdf:subject, rdf:object should be replaced by the relevant property of the qualified relation as well like ex:partner in the example since rdf:Statement, rdf:subject, rdf:predicate, rdf:object are used for reification [2]?

[1]. http://patterns.dataincubator.org/book/qualified-relation.html
[2]. http://www.obitko.com/tutorials/ontologies-semantic-web/rdf-elements.html

---

Qualified relation example in the link [1]:

eg:bob a foaf:Person.
eg:mary a foaf:Person.

_:bobMaryMarriage a ex:Marriage;
    ex:partner eg:bob;
    ex:partner eg:mary;
    ex:date "2009-04-01"^^xsd:date.

---

Take the qualified relation of ["Following"](https://github.com/w3c-social/social-vocab/tree/master/qualified-relation/Following) as an example:

https://wwelves.org/perpetual-tripper/rel/3242 a :Following ;
  as:actor (or other newly defined property) https://wwelves.org/perpetual-tripper ;
  as:object (or other newly defined property) https:/rhiaro.co.uk ;
  :startTime "16 July 2014" .

**Comment by elf-pavlik** [comment]
Hi @parklize 

I see need to align work on Social WG wiki and in this repository. Here I mostly wanted to focus on visualizing the actual graphs. I also hope that we can reuse as much as possible from existing terms and make this repsitory more of an extended documentation.

I don't have clear strategy for Qualified Relation yet. We should also take a look at [schema:Role](http://schema.org/Role]
- http://blog.schema.org/2014/06/introducing-role.html

![schema:Role](http://4.bp.blogspot.com/-jf3x5HkGVF8/U58cxdWKZoI/AAAAAAAAI5g/bIha2aZn3Ek/s1600/sdo-athlete-role.png)

![schema:Role](http://3.bp.blogspot.com/-9ZNmMYVIvkQ/U58dliwFPbI/AAAAAAAAI5s/KociBJuFDBo/s1600/sdo-ghostbusters-role.png)

In next days I will not stay very responsive here, hitchhiking for our face 2 face in Paris...

**Comment by parklize** [comment]
Sure, we could discuss it in more detail next week.
